### ISSUE TITLE
command 'extension.runCypress' not found

### ISSUE THREAD

**Issue by mjgoeke** [tnrich/vscode-extension-open-cypress#2]
Vscode toasts up an error when I try to run the `Run Cypress` or `Run Cypress Single it Block` command.
When running the command `Run Cypress` through the vscode command palette vscode toasts an error saying:
(x) `command 'extension.runCypress' not found`

For `Run Cypress Single it Block`, same sort of error, but it says
(x) `command 'extension.runCypressOnly' not found`

I have a fully functional cypress project set up, package.json with scripts that run `cypress open` and the rest just fine.
Are there other prerequisites I'm missing before this extension will work?

**Comment by tnrich** [comment]
@mjgoeke nope I'm seeing that as well! Gimme a minute and I'll try to fix it :)

**Comment by tnrich** [comment]
Okay, published vscode-extension-open-cypress@0.0.10 

Lemme know if that helps
