### ISSUE TITLE
local/custom cypress location

### ISSUE THREAD

**Issue by vsix27** [tnrich/vscode-extension-open-cypress#7]
currently extension run "cypress ...." command
however, cypress could be installed as a local package and there is no global variable for cypress.
so when running from VSCode - instead of "cypress ..." i would like to use "node_modules/.bin/cypress ...",
not sure where i can change that configuration...

**Comment by tnrich** [comment]
Happy to accept a PR for that @vsix27 :)

**Comment by vsix27** [comment]
thank you, actually i found easy fix for this 
add to your system variables/windows to PATH
node_modules\\.bin

**Comment by tnrich** [comment]
Glad to hear it @vsix27 !
